default_stages: [commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.0.1'
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-case-conflict
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      # - id: check-shebang-scripts-are-executable # support in lastest ref
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.17.12
    hooks:
      - id: commitizen
        stages: [commit-msg]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v2.3.2'
    hooks:
      - id: prettier
  - repo: https://github.com/pre-commit/mirrors-yapf
    rev: 'v0.31.0'
    hooks:
      - id: yapf
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.20.0
    hooks:
      - id: pyupgrade
  - repo: https://github.com/yoheimuta/protolint
    rev: v0.32.0
    hooks:
      - id: protolint
  # - repo: https://github.com/markdownlint/markdownlint
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.27.1
    hooks:
      - id: markdownlint
  - repo: https://github.com/rubocop/rubocop
    rev: v1.18.3
    hooks:
      - id: rubocop
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.7.2.1
    hooks:
      - id: shellcheck
  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
      - id: cmake-format
      - id: cmake-lint
  - repo: https://gist.github.com/curoky/cd141455853d28e61b61e54220a7eaa5
    rev: 'acce1461f3d6b20eecb0fb4464d88f2fee2fc958'
    hooks:
      - id: shfmt
      - id: buildifier
      - id: clang-format
      - id: cpplint
      - id: cppcheck
      - id: bean-format
      - id: isort
      - id: licenseheaders
        args:
          [
            '--years',
            '2020',
            '--exclude',
            '*.rb',
            '*.md',
            '*.yml',
            '*.yaml',
            '*.rb',
            '--files',
          ]
