name: build thriftc
on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/build-thriftc.yaml'
      - 'Formula/thriftc.rb'
      - 'src/actions/action.yaml'

jobs:
  install:
    strategy:
      fail-fast: false
      max-parallel: 20
      matrix:
        version:
          - '0.8.0'
          - '0.9.0'
          - '0.9.1'
          - '0.9.2'
          - '0.9.3'
          - '0.9.3.1'
          - '0.10.0'
          - '0.11.0'
          - '0.12.0'
          - '0.13.0'
          - '0.14.1'

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./src/actions
        with:
          formula: thriftc
          install_args: --verbose --build-from-source
          test_args: --verbose
          env: 'HOMEBREW_THRIFTC_VERSION=${{ matrix.version }}'
          ggg: ${{ secrets.GH_UPLOAD_KEY }}
          upload_filepath: /home/linuxbrew/.linuxbrew/opt/thriftc/bin/thrift
          upload_filename: thrift-${{ matrix.version }}
