name: build protoc
on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/build-protoc.yaml'
      - 'Formula/protoc.rb'
      - 'src/actions/action.yaml'

jobs:
  install:
    strategy:
      fail-fast: false
      max-parallel: 20
      matrix:
        version:
          - '3.1.0'
          - '3.2.0'
          - '3.3.2'
          - '3.4.1'
          - '3.5.2'
          - '3.7.1'
          - '3.8.0'
          - '3.9.2'
          - '3.13.0.1'
          - '3.14.0'
          - '3.15.6'
          - '3.16.0'
          - '3.17.3'

    runs-on: ubuntu-latest
    container:
      image: homebrew/ubuntu20.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./src/actions
        with:
          formula: protoc
          install_args: --verbose --build-from-source
          test_args: --verbose
          env: 'HOMEBREW_PROTOC_VERSION=${{ matrix.version }}'
          ggg: ${{ secrets.GITHUB_TOKEN }}
          upload_filepath: /home/linuxbrew/.linuxbrew/opt/protoc/bin/protoc
          upload_filename: protoc-${{ matrix.version }}
