name: build cask
on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/build-cask.yaml'
      - 'Cask/*.rb'
  schedule:
    - cron: '0 0 * * 1'

jobs:
  build_cask:
    runs-on: macos-latest
    env:
      HOMEBREW_NO_ANALYTICS: 1
      HOMEBREW_NO_AUTO_UPDATE: 1

    steps:
      - uses: actions/checkout@v2

      - name: link tap
        run: |
          mkdir -p $(brew --repo)/Library/Taps/curoky
          cp -r $PWD $(brew --repo)/Library/Taps/curoky/homebrew-tap

      - name: install cask
        run: brew install freefilesync --cask
