name: test on osx
on:
  push:

jobs:
  install:
    strategy:
      fail-fast: false
      max-parallel: 100
      matrix:
        os: [macos-latest]
        package:
          # ls Formula | xargs -n 1 | sed -e 's/.rb/ /' -e 's/^/          - /'
          # - apfs-fuse
          - bazel@3
          - bazel-buildtools
          - bazel-compilation-database
          - chkservice
          - cmake-format
          - flamegraph@2
          - git-mv-with-history
          # - glibc2.32
          - include-what-you-use@15
          # - libevent-openssl1.0
          # - libfuse@3
          # - libiberty
          # - llvm-latest
          # - miniconda
          # - ncurses@5
          # - ncurses-termlib
          # - openssl@1.0.2t
          # - openssl@1.0.2u
          # - oracle-jdk
          - python@2
          - qt@5.13.2
          - rime-bundle
          - terminalizer
          # - thrift@0.9.3
          - typora-bundle
          - vim-bundle
          - zsh-bundle

    runs-on: ${{ matrix.os }}

    env:
      HOMEBREW_NO_ANALYTICS: 1
      HOMEBREW_NO_AUTO_UPDATE: 1

    steps:
      - uses: actions/checkout@v2

      - name: check if the platform supports
        run: |
          if grep -q "depends_on :linux" ./Formula/${{ matrix.package }}.rb; then
            echo "ignore=true" >> $GITHUB_ENV
          fi

      - uses: curoky/actions/brew-tap-install-test@master
        if: env.ignore != 'true'
        with:
          formula: ${{ matrix.package }}
          install_args: '--include-test'

  install_cask:
    runs-on: macos-latest
    env:
      HOMEBREW_NO_ANALYTICS: 1
      HOMEBREW_NO_AUTO_UPDATE: 1

    steps:
      - uses: actions/checkout@v2

      - name: link tap
        run: |
          mkdir -p $(brew --repo)/Library/Taps/curoky
          cp -r $PWD $(brew --repo)/Library/Taps/curoky/homebrew-tap

      - name: install cask
        run: brew install freefilesync --cask
