name: test on linux
on:
  push:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  install:
    strategy:
      fail-fast: false
      max-parallel: 100
      matrix:
        os: [ubuntu16.04, ubuntu18.04, ubuntu20.04]
        package:
          - bazel-buildtools
          - bazel-compilation-database
          - bazel@3
          - cmake-format
          - cpplint
          - gost
          - hexo
          - include-what-you-use@15
          - libevent-openssl1.0
          - llvm@11
          - miniconda
          - ncurses@5
          - openssl@1.0.2t
          - openssl@1.0.2u
          - oracle-jdk

    runs-on: ubuntu-latest

    container:
      image: homebrew/${{ matrix.os }}

    env:
      HOMEBREW_NO_ANALYTICS: 1
      HOMEBREW_NO_AUTO_UPDATE: 1

    steps:
      - uses: actions/checkout@v2
      - uses: curoky/actions/brew-tap-install-test@master
        with:
          formula: ${{ matrix.package }}
