name: test on linux
on:
  push:

jobs:
  install:
    strategy:
      fail-fast: false
      max-parallel: 100
      matrix:
        os: [ubuntu16.04, ubuntu18.04, ubuntu20.04]
        package:
          # ls Formula | xargs -n 1 | sed -e 's/.rb/ /' -e 's/^/          - /'
          - bazel@3
          - bazel-buildtools
          - bazel-compilation-database
          # - cmake-format        # Note: not completed
          - cpplint
          - git-mv-with-history
          - gost
          - hexo
          - include-what-you-use@15
          - libevent-openssl1.0
          - llvm@11
          - miniconda
          - ncurses@5
          - openssl@1.0.2t
          - openssl@1.0.2u
          - oracle-jdk
          - python@2_linux
          # - python@2_osx        # Note: osx only
          - thrift@0.9.3
          - typora-bundle
          - vim-bundle
          - zsh-bundle

    runs-on: ubuntu-latest

    container:
      image: homebrew/${{ matrix.os }}

    env:
      HOMEBREW_NO_ANALYTICS: 1
      HOMEBREW_NO_AUTO_UPDATE: 1

    steps:
      - uses: actions/checkout@v2
      - uses: curoky/actions/brew-tap-install-test@master
        with:
          formula: ${{ matrix.package }}
