name: test on linux
on:
  push:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  install:
    strategy:
      fail-fast: false
      max-parallel: 100
      matrix:
        os: [ubuntu16.04, ubuntu20.04] # ubuntu18.04,
        package:
          # ls Formula | xargs -n 1 | sed -e 's/.rb/ /' -e 's/^/          - /'
          - apfs-fuse
          - bazel@3
          - bazel-buildtools
          - bazel-compilation-database
          # - boost@1.57.0
          - boost@1.60.0
          - boost@1.72.0
          - chkservice
          - cmake-format
          - fbthrift@2021.02.15
          - fizz@2021.02.15
          - flamegraph@2
          - folly@2021.02.15
          - git-mv-with-history
          - glibc2.32
          # - include-what-you-use@15
          - libiberty
          - ncurses@5
          - openssl@1.0.2t
          - openssl@1.0.2u
          - python@2
          - qt@5.13.2
          - rime-bundle
          - terminalizer
          - typora-bundle
          - vim-bundle
          - wangle@2021.02.15
          - zsh-bundle

    runs-on: ubuntu-latest

    container:
      image: homebrew/${{ matrix.os }}

    env:
      HOMEBREW_NO_ANALYTICS: 1
      HOMEBREW_NO_AUTO_UPDATE: 1

    steps:
      - uses: actions/checkout@v2

      - name: check if the platform supports
        run: |
          if grep -q "depends_on :macos" ./Formula/${{ matrix.package }}.rb; then
            echo "ignore=true" >> $GITHUB_ENV
          fi

      - name: test source
        uses: curoky/actions/brew-tap-install-test@master
        if: env.ignore != 'true'
        with:
          formula: ${{ matrix.package }}
          install_args: "--include-test --build-from-source"

      - name: remove package
        run: brew remove ${{ matrix.package }}

      - name: test bottle
        uses: curoky/actions/brew-tap-install-test@master
        if: env.ignore != 'true'
        with:
          formula: ${{ matrix.package }}
          install_args: "--include-test"
