name: test on osx
on:
  push:

jobs:
  install:
    strategy:
      fail-fast: false
      max-parallel: 100
      matrix:
        os: [macos-latest]
        package:
          # ls Formula | xargs -n 1 | sed -e 's/.rb/ /' -e 's/^/          - /'
          - bazel@3
          # - bazel-buildtools  # Note: linux only
          - bazel-compilation-database
          # - cmake-format      # Note: not completed
          - cpplint
          - gost
          - hexo
          - include-what-you-use@15
          - libevent-openssl1.0
          - llvm@11
          # - miniconda         # Note: linux only, osx has cask one
          # - ncurses@5         # Note: linux only
          - openssl@1.0.2t
          # - openssl@1.0.2u    # Note: linux only
          # - oracle-jdk        # Note: linux only, osx has cask one
          # - python@2_linux    # Note: linux only
          - spaceship-prompt
          # - thrift@0.9.3      # Note: Error: libcrypto required.
          - typora-bundle
          - vim-bundle
          - zsh-bundle

    runs-on: ${{ matrix.os }}

    env:
      HOMEBREW_NO_ANALYTICS: 1
      HOMEBREW_NO_AUTO_UPDATE: 1

    steps:
      - uses: actions/checkout@v2

      - name: unlink preinstall nodejs
        run: brew unlink node@12

      - name: remove openssl@1.0.2t in local tap
        run: rm -rf $(brew --repo)/Library/Taps/local

      - uses: curoky/actions/brew-tap-install-test@master
        with:
          formula: ${{ matrix.package }}
