name: test on linux
on:
  push:

jobs:
  install:
    strategy:
      fail-fast: false
      max-parallel: 100
      matrix:
        os: [ubuntu16.04, ubuntu20.04] # ubuntu18.04,
        package:
          # ls Formula | xargs -n 1 | sed -e 's/.rb/ /' -e 's/^/          - /'
          - bazel@3
          - bazel-buildtools
          - bazel-compilation-database
          # - cmake-format
          - flamegraph@2
          - git-mv-with-history
          - glibc2.32
          - include-what-you-use@15
          - libevent-openssl1.0
          - libfuse@3
          - libiberty
          # - llvm-latest
          - miniconda
          - ncurses@5
          - ncurses-termlib
          - openssl@1.0.2t
          - openssl@1.0.2u
          - oracle-jdk
          - python@2
          - qt@5.13.2
          - terminalizer
          - thrift@0.9.3
          - typora-bundle
          - vim-bundle
          - zsh-bundle

    runs-on: ubuntu-latest

    container:
      image: homebrew/${{ matrix.os }}

    env:
      HOMEBREW_NO_ANALYTICS: 1
      HOMEBREW_NO_AUTO_UPDATE: 1

    steps:
      - uses: actions/checkout@v2

      - name: prepare deps
        if: ${{ matrix.os == 'ubuntu16.04' }}
        run: |
          sudo apt update
          sudo apt install libisl-dev
          sudo ln -s /usr/lib/x86_64-linux-gnu/libisl.so /usr/lib/x86_64-linux-gnu/libisl.so.22

      - name: homebrew cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/Homebrew
          key: ${{ matrix.package }}-${{ hashFiles(format('Formula/{0}.rb', matrix.package)) }}
          restore-keys: |
            ${{ matrix.package }}-

      - name: check cache
        run: |
          mkdir -p ~/.cache/Homebrew || echo "ignore exits"
          ls -la $(brew --cache)

      - name: upgrade homebrew
        run: brew update && brew upgrade || echo "ignore failed"

      - uses: curoky/actions/brew-tap-install-test@master
        with:
          formula: ${{ matrix.package }}
          install_args: "--include-test"
