name: test on linux
on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/test-linux.yaml'
      - 'Formula/**'
      - 'src/lib/**'
  schedule:
    - cron: '0 0 * * 1'

jobs:
  install:
    strategy:
      fail-fast: false
      max-parallel: 100
      matrix:
        os: [ubuntu16.04, ubuntu20.04] # ubuntu18.04,
        package:
          # ls Formula | xargs -n 1 | sed -e 's/.rb/ /' -e 's/^/          - /'
          - apfs-fuse
          - bazel-compilation-database
          - bazel
          - boost@1.57.0
          - boost@1.60.0
          - boost@1.72.0
          - cmake-format
          - fbthrift@2021.02.15
          - fizz@2021.02.15
          - flamegraph
          - folly@2021.02.15
          - gflags@2.2.2
          - git-mv-with-history
          - glibc@2.32
          - libiberty
          - ncurses@5
          - openssl@1.0.2t
          - openssl@1.0.2u
          - python@2
          - qt@5.13.2
          - rime-bundle
          - terminalizer
          - vim-bundle
          - wangle@2021.02.15
          - zsh-bundle

    runs-on: ubuntu-latest

    container:
      image: homebrew/${{ matrix.os }}

    env:
      HOMEBREW_NO_ANALYTICS: 1
      HOMEBREW_NO_AUTO_UPDATE: 1

    steps:
      - uses: actions/checkout@v2

      - name: check if the platform supports
        run: |
          if grep -q "depends_on :macos" ./Formula/${{ matrix.package }}.rb; then
            echo "ignore=true" >> $GITHUB_ENV
          fi

      - uses: ./src/actions
        if: env.ignore != 'true'
        with:
          formula: ${{ matrix.package }}
          install_args: '--include-test --verbose' # --build-from-source
          test_args: --verbose
